# Q.1 Write a Python code to create an array of 5 integers and display the array items. Accessindividual element through indexes.

In [17]:
# import numpy as np
# a = [1,2,3,5,6,8,254,4]
# arr = np.array(a)
# # Access individual element through indexes
# print(f"The Orignal Array Is : {arr}")
# print("Access individual element through indexes :- ")

# # 1st way
# for i in range(0,len(arr)):
#     print(f"Index no {i} =>{arr[i]} ")
# print()
    
# # 2nd Way
# print(f"Index no 0 =>",arr[0])
# print(f"Index no 1 =>",arr[1])
# print(f"Index no 2 =>",arr[2])
# print(f"Index no 3 =>",arr[3])
# print(f"Index no 4 =>",arr[4])
# print(f"Index no 5 =>",arr[5])
# print(f"Index no 6 =>",arr[6])
# print(f"Index no 7 =>",arr[7])


# # 3 Way 
# print("3 way ",arr[0:])

# 2nd Mehtod
from array import *
a = [1,2,5,6,4,8,78]
arr = array('i',a)
print("The Original Array is ",arr)
print()
print("Accessing Array Through different Indexes : ")
for i in range(0,len(arr)):
    print(f"{[i]} =>",arr[i],end=" ")



    
    

The Original Array is  array('i', [1, 2, 5, 6, 4, 8, 78])

Accessing Array Through different Indexes : 
[0] => 1 [1] => 2 [2] => 5 [3] => 6 [4] => 4 [5] => 8 [6] => 78 

# Q.2 Write a Python code to reverse the order of the items in the array.

In [66]:
from numpy import * 
# a = [1,5,8,4,7,89,74,45]
# arr = array(a)


# 1 Way
# print("The Original Array is :",arr)
# print("Array In Reverse Order is : ",end="[ ")
# for i in range(len(arr)-1,-1,-1):
#     print(arr[i],end=" ")
# print("]")


# 2 Way 
# print("The Original Array is : ",arr)
# print("The Array in reverse Order is : ",arr[::-1])

# 2 Method
from array import *
a = [1,5,8,4,7,69,45]
arr = array('i',a)

# 1 Way 
# print("The Original Array is : ",arr)
# arr.reverse()# this is used to reverse the array
# print("The Array in reverse order is : ",arr)


# 2 Way
print("The Original Array is : ",arr)
print("The Array In Reverse order is :",arr[::-1])

 

The Original Array is :  array('i', [1, 5, 8, 4, 7, 69, 45])
The Array In Reverse order is : array('i', [45, 69, 7, 4, 8, 5, 1])


# Q.3 Write a Python code to get thenumber of occurrences of a specified element in anarray


In [50]:
import numpy as np

# a = [10,5,2,8,2,2,2,5,6,8,6,8,2,1,4,5]
# arr = np.array(a)
# print("The Original Array is : ",arr)
# num = int(input("Enter A number : "))
# count = np.count_nonzero(arr == num)
# count = (arr == num).sum() # alternate way
# print(f"The Total Number of occurrences of {num} is {count} ")


# 2 Method
from array import *
a = [10,50,2,5,4,6,2,7,8,2,1,2]
arr = array('i',a)
print("The Original Array is : ",arr)
num = int(input("Enter A Number : "))
count = arr.count(num)
print(f"The Frequency of {num} in array  is {count}")


The Original Array is :  array('i', [10, 50, 2, 5, 4, 6, 2, 7, 8, 2, 1, 2])
Enter A Number : 2
The Total Number of occurrences of 2 is 4


# Q.4 Write a python program to sort array with any sorting algorithm.(e.g. bubble sort, quicksort)

In [114]:
import numpy as np
a = [10,25,4,1,2,8,6,96,1]
arr = np.array(a)

# Defining a Function for Bubble sort
def bubble_sort(a):
    n = len(a)
    temp = 0
    for i in range(n):
        for j in range(i+1,n):
            if(a[i]>a[j]):
                temp = a[i]
                a[i] = a[j]
                a[j] = temp
    return a

print("The Original Array is : ",arr)
# calling a function
bubble_sort(arr)
print("The Array after Bubble Sorting is : ",arr)

# sorting using function
# print("The Array sort Using sort function",np.sort(arr))


The Original Array is :  [10 25  4  1  2  8  6 96  1]
The Array sort Using sort function [ 1  1  2  4  6  8 10 25 96]


# Q.5 Write a python program to convert 2-D 3*3 matrix values in to zero to one

In [113]:
import numpy as np
# arr = np.arange(1,10).reshape(3,3)
ar = np.eye(3)
# arr = np.identity(3)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Q.6 Write a python program to create inverse of 3*3 matrix.

In [97]:
import numpy as np
arr = np.array([[2,5,9],[4,2,3],[4,9,1]])
print("The Matrix is :")
print(arr)
# Calculate Determinant
determinant = np.linalg.det(arr)
print()
if(determinant !=0):
    inverse = np.linalg.inv(arr)
    print("The Inverse Of Given Matrix Is : \n")
    print(inverse)
else:
    print("The Inverse of given Mathrix is not possible becuase Determinant is 0 ")
    

The Matrix is :
[[2 5 9]
 [4 2 3]
 [4 9 1]]

The Inverse Of Given Matrix Is : 

[[-0.10330579  0.31404959 -0.01239669]
 [ 0.03305785 -0.14049587  0.12396694]
 [ 0.11570248  0.00826446 -0.0661157 ]]


# Q.7 Create Python function to generate log values of 3*5 matrix.

In [118]:

import numpy as np
arr = np.arange(15,30).reshape(3,5)
print("The Matrix is : ")
print(arr)
print()

# Function defining
def find_log(arr):
    rows = arr.shape[0]
    cols = arr.shape[1]
    for i in range(rows):
        for j in range(cols):
            print(np.log(arr[i][j]),end = " ")
        print()
        
# Calling Function

find_log(arr)        

The Matrix is : 
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

2.70805020110221 2.772588722239781 2.833213344056216 2.8903717578961645 2.9444389791664403 
2.995732273553991 3.044522437723423 3.091042453358316 3.1354942159291497 3.1780538303479458 
3.2188758248682006 3.258096538021482 3.295836866004329 3.332204510175204 3.367295829986474 


In [120]:
import numpy as np
matrix = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
log_matrix = np.log(matrix)
print("Log values of matrix:\n", log_matrix)

Log values of matrix:
 [[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
 [2.39789527 2.48490665 2.56494936 2.63905733 2.7080502 ]]
