In [1]:
import numpy as np

In [2]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
arr = np.array(x)

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr.shape

(3, 3)

In [9]:
arr.sum(axis=0)

array([12, 15, 18])

In [10]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [11]:
# arrayname.T is used to transpose the array

In [12]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
# to iterate items of array using for loop
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [18]:
# arrayname.ndim is used to return dimensions
arr.ndim

2

In [19]:
# arrayname.size is used to get size of and it means how many elements are there in an array
arr.size

9

In [21]:
# This attribute is used to find how many bytes occupied by the array
arr.nbytes

36

In [22]:
one = np.array([1,3,4,634,2])

In [23]:
# This method is sued to find index to maximum element in the array
one.argmax()

3

In [24]:
# This method is used to find index of minimum or lowest element in an array 
one.argmin()

0

In [25]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [26]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.argmin()

0

In [28]:
arr.argmax()

8

In [29]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [30]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [31]:
arr2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [32]:
arr + arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [33]:
arr * arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [34]:
# this method provides array of square root of every element present in an array
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [35]:
arr.sum()

45

In [36]:
arr.max()

9

In [37]:
arr.min()

1

In [39]:
np.count_nonzero(arr)

9