In [1]:
import numpy as np

In [2]:
l1 = [1,3,55,2]

In [4]:
myarr = np.array(l1)

In [5]:
print(myarr)

[ 1  3 55  2]


In [6]:
myarr

array([ 1,  3, 55,  2])

# using numpy we can easily manage memory... like
# np.int32,np.int64

In [23]:
myarr = np.array(l1,np.int8)

In [9]:
print(type(myarr),myarr)

<class 'numpy.ndarray'> [ 1  3 55  2]


In [24]:
myarr

array([ 1,  3, 55,  2], dtype=int8)

In [12]:
myarr

array([ 1,  3, 55,  2])

In [25]:
arr = np.array(l1, np.int64)

In [26]:
arr

array([ 1,  3, 55,  2], dtype=int64)

In [27]:
arr[0]

1

# To identitfy number of row and column in array we used arr.shape

In [39]:
arr.shape


(4,)

In [29]:
arr.dtype # it used to idntify type of datatype

dtype('int64')

# Array Creation : Conversion from otheer Pyhton Structures

In [46]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [47]:
listarray.shape

(3, 3)

In [48]:
listarray.dtype


dtype('int32')

In [49]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [34]:
print(listarray)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [35]:
listarray.size

9

In [36]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [52]:
# np.zeros funxtion i used to provide a zeor matrix by providing size as row and column
zeros = np.zeros((2,5))

In [38]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
# np.arange is used to an array starting from 0 to specified number -1
rng = np.arange(15)


In [51]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
lspace = np.linspace(1,4,3)

In [54]:
lspace

array([1. , 2.5, 4. ])

In [55]:
#  It will give an empty array pf given size like 4,6 and it is fufllied by random values
emp = np.empty((4,6))


In [56]:
emp

array([[6.23042070e-307, 7.56587584e-307, 1.37961302e-306,
        6.23053614e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 9.34598925e-307,
        1.42418715e-306, 1.95819401e-306, 1.37961370e-306],
       [6.23054633e-307, 9.34598926e-307, 6.89804132e-307,
        9.34598926e-307, 1.86919513e-306, 9.34604358e-307],
       [2.22522597e-306, 6.89812960e-307, 1.42419530e-306,
        9.34609790e-307, 2.22522596e-306, 2.56765117e-312]])

In [57]:
# np.empty_like is used to create an empty by specifing and another array name and take it size and create and empty array
emp_like = np.empty_like(lspace)

In [58]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [61]:
arr = np.arange(99)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [63]:
# array,reshape is used to reshape an array by specifying a size and multiply row and column than it must be a number as same as spcified
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# converting in 2 d array`

In [65]:
arr  =  arr.reshape(3,33)

In [66]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

# coverting to 1d array

In [67]:
# arrayname.ravel isused to convert 2d Array into 1 Array
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [68]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])