In [1]:
# Tuple is collection of oredered data items which can be of different data types
# Tuples are immutable,i.e..not changeable
# Tuples are defined in parenthesis


In [2]:
a = (1,2,3,40,25,60)

In [3]:
print(a)

(1, 2, 3, 40, 25, 60)


In [4]:
# Converting tuple into lists
b = [1,2,3,8,9,45]
print(tuple(b))

(1, 2, 3, 8, 9, 45)


In [6]:
# printing Tuple elements
for i in a:
    print(i,end=" ")

1 2 3 40 25 60 

# Tuple Indexing

In [9]:
# Elements in tuple alwyas start with 0th index
name = ("Raj","Prasham","Akshat","abc")
i = 0
while i<len(name):
    print(name[i],end=" ")
    i+=1

Raj Prasham Akshat abc 

In [10]:
print(name[-1])
print(name[-2])
print(name[-3])
print(name[-4])

abc
Akshat
Prasham
Raj


# Tuple Silicing

In [12]:
# If we want slice multiple values from a tuple,we can ":" operator
print(name[:])
print(name[0:])
print(name[:2])
print(name[::-1])

('Raj', 'Prasham', 'Akshat', 'abc')
('Raj', 'Prasham', 'Akshat', 'abc')
('Raj', 'Prasham')
('abc', 'Akshat', 'Prasham', 'Raj')


# Skipping elements while slicing 

In [13]:
print(name[0:len(name):1])

('Raj', 'Prasham', 'Akshat', 'abc')


In [14]:
print(name[0:len(name):2])

('Raj', 'Akshat')


In [15]:
print(name[0:len(name):3])

('Raj', 'abc')


In [3]:
import numpy as np

n = 5  # size of the array
a = np.ones((5,5))  # create an array of ones and zeros
a[range(n), range(n)] = 0  # set the diagonal to zero

print(a)


[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]
